### ISSUE TITLE
Make protocol actions more explicit

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/service-protocol#28]
For some SDKs, it could be helpful to make certain protocol actions such as suspending more explicit by sending an explicit message instead of only closing the request channel. It would have the benefit that a runtime failure which also closes the request channel can be easily distinguished from a suspension. Some languages/frameworks have difficulties detecting the difference right now (see https://restatedev.slack.com/archives/C04KZRLE1SM/p1687219253254139 for more details).

**Comment by slinkydeveloper** [comment]
This task is not really actionable right now, will close this.
