### ISSUE TITLE
Make suspensions an optional feature

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/service-protocol#31]
When implementing the new TS SDK, the runtime initiated suspension mechanism made the implementation harder. It would be simpler for a new SDK to be able to ignore this feature altogether if possible. One idea could be to let the SDK tell the runtime whether it supports runtime initiated suspensions (w/o it, the SDK would probably not work on AWS lambda, though). 

Another simplification could be to allow the `waiting_for_completed_entries` field to be empty which denotes that the invocation will be resumed on any journal entry completion.

More details are needed for why the suspension mechanism caused trouble (Stephan, Giselle).

**Comment by slinkydeveloper** [comment]
This task is not really actionable right now, will close this.
