### ISSUE TITLE
Make the journal an immutable log by storing completions separately

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/service-protocol#32]
Implementing new SDKs could become easier for the journal would be an immutable log of journal entries and completions that are stored separately. This would allow us to remove the need for completable and non-completable journal entries. It could also help with implementing deterministic futures since we record in which order the journal entries are completed.

One problem that might arise is that with this change, there will be two components that append to the journal: the runtime which appends completions and the SDK appending journal entries. Right now, only the SDK is allowed to append journal entries which makes it quite simple to keep the runtime and SDK view on the journal in sync.

In order to solve this problem, the SDK would probably need to be able to re-order the tail of its journal in case there were completions that were appended before the last journal entries.

A minor disadvantage is that the runtime will lose the cheap capability to check whether a journal entry was completed or not.

More details on how an immutable log can simplify the SDK implementation are needed (Stephan, Giselle).

**Comment by slinkydeveloper** [comment]
This task is not really actionable right now, will close this.
