### ISSUE TITLE
Finish the invocation with the first OutputStreamEntry

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/service-protocol#33]
One problem the TS SDK ran into was that a replay could happen after the first `OutputStreamEntry` was sent. Given that we don't support output streaming (yet and probably in the foreseeable future), we might consider changing the protocol such that an invocation terminates with the first and only `OutputStreamEntry`.

**Comment by slinkydeveloper** [comment]
This is not valid anymore. See https://github.com/restatedev/service-protocol/issues/49
